--CREATE DATABASE SKINART

USE SKINART;

GO

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
	NOME_USUARIO VARCHAR(200) NOT NULL,
	SOBRENOME_USUARIO VARCHAR(200) NOT NULL,
	DATA_NASC_USUARIO DATE NOT NULL,
	CPF_USUARIO VARCHAR(14) UNIQUE NOT NULL,
	RG_USUARIO VARCHAR(15) NOT NULL,
	LOGIN_USUARIO VARCHAR(200) UNIQUE NOT NULL,
	SENHA_USUARIO VARCHAR(200) NOT NULL
);
GO

CREATE TABLE PAPEL (
	ID_PAPEL INT PRIMARY KEY IDENTITY(1,1),
	NOME_PAPEL VARCHAR(50) NOT NULL 
);
GO

CREATE TABLE USUARIO_PAPEL (
	ID_USUARIO INT NOT NULL,
	ID_PAPEL INT NOT NULL,
	PRIMARY KEY (ID_USUARIO, ID_PAPEL),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	FOREIGN KEY (ID_PAPEL) REFERENCES PAPEL(ID_PAPEL)
);
GO

CREATE TABLE TATUADOR (
	ID_USUARIO INT PRIMARY KEY,
	DESCRICAO_TATUADOR VARCHAR(500) NOT NULL,
	CNAE_FORMACAO_TATUADOR VARCHAR(100) NOT NULL,
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
GO

CREATE TABLE ARTE_TATUADOR (
	ID_ARTE_TATUADOR INT PRIMARY KEY IDENTITY(1,1),
	ID_TATUADOR INT NOT NULL,
	IMAGEM_PATH_ARTE_TATUADOR VARCHAR(300) NOT NULL,
	DESC_ARTE_TATUADOR VARCHAR(200),
	FOREIGN KEY (ID_TATUADOR) REFERENCES TATUADOR(ID_USUARIO)
);
GO

CREATE TABLE AGENDAMENTO (
	ID_AGENDAMENTO INT PRIMARY KEY IDENTITY(1,1),
	DATA_AGENDAMENTO DATE NOT NULL,
	HORA_AGENDAMENTO TIME NOT NULL,
	ID_TATUADOR INT NOT NULL,
	FOREIGN KEY (ID_TATUADOR) REFERENCES TATUADOR(ID_USUARIO)
);
GO

CREATE TABLE STATUS_PAGAMENTO (
	ID_STATUS_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
	STATUS_PAGAMENTO VARCHAR(20) NOT NULL
);
GO

CREATE TABLE PAGAMENTO (
	ID_PAGAMENTO INT PRIMARY KEY IDENTITY(1,1),
	TIPO_PAGAMENTO VARCHAR(30) NOT NULL,
	DATA_PAGAMENTO DATE NOT NULL,
	HORA_PAGAMENTO TIME NOT NULL,
	PARCELAMENTO_PAGAMENTO TINYINT,
	ID_STATUS_PAGAMENTO INT NOT NULL,
	ID_TATUADOR INT NOT NULL,
	FOREIGN KEY (ID_STATUS_PAGAMENTO) REFERENCES STATUS_PAGAMENTO(ID_STATUS_PAGAMENTO),
	FOREIGN KEY (ID_TATUADOR) REFERENCES TATUADOR(ID_USUARIO)
);
GO

--CREATE TABLE SALARIO (
--	ID_SALARIO INT PRIMARY KEY IDENTITY(1,1),
--	ID_TATUADOR INT NOT NULL,
--	VALOR_SALARIO DECIMAL(10,2) NOT NULL,
--	DATA_CAIMENTO_SALARIO DATE NOT NULL,
--	FOREIGN KEY (ID_TATUADOR) REFERENCES TATUADOR(ID_USUARIO)
--);
--GO



--============================== INSERT TESTE ==================================

INSERT INTO USUARIO (
	NOME_USUARIO, SOBRENOME_USUARIO, DATA_NASC_USUARIO, CPF_USUARIO,
	RG_USUARIO, LOGIN_USUARIO, SENHA_USUARIO
) VALUES (
	'João', 'Silva', '1990-05-15', '123.456.789-00',
	'12.345.678-9', 'joao.silva', 'senha123'
);

INSERT INTO PAPEL (NOME_PAPEL) VALUES ('Tatuador');
INSERT INTO PAPEL (NOME_PAPEL) VALUES ('Admin');

INSERT INTO USUARIO_PAPEL (ID_USUARIO, ID_PAPEL) VALUES (1, 1); -- Tatuador
INSERT INTO USUARIO_PAPEL (ID_USUARIO, ID_PAPEL) VALUES (1, 2); -- Admin

INSERT INTO TATUADOR (
	ID_USUARIO, DESCRICAO_TATUADOR, CNAE_FORMACAO_TATUADOR
) VALUES (
	1, 'Especialista em tatuagem realista', '9602501'
);

INSERT INTO ARTE_TATUADOR (
	ID_TATUADOR, IMAGEM_PATH_ARTE_TATUADOR, DESC_ARTE_TATUADOR
) VALUES (
	1, 'imagens/arte_dragon.png', 'Dragão japonês em estilo realista'
);

INSERT INTO STATUS_PAGAMENTO (STATUS_PAGAMENTO) VALUES ('Pendente');
INSERT INTO STATUS_PAGAMENTO (STATUS_PAGAMENTO) VALUES ('Pago');

--INSERT INTO PAGAMENTO (
--	TIPO_PAGAMENTO, DATA_PAGAMENTO, HORA_PAGAMENTO, PARCELAMENTO_PAGAMENTO,
--	ID_STATUS_PAGAMENTO, ID_TATUADOR
--) VALUES (
--	'Cartão de Crédito', '2025-06-24', '15:30:00', 3,
--	2, -- 'Pago'
--	1
--);


--DROP TABLE IF EXISTS PAGAMENTO;
--DROP TABLE IF EXISTS SALARIO;
--DROP TABLE IF EXISTS ARTE_TATUADOR;
--DROP TABLE IF EXISTS AGENDAMENTO;
--DROP TABLE IF EXISTS STATUS_PAGAMENTO;
--DROP TABLE IF EXISTS TATUADOR;
--DROP TABLE IF EXISTS ADMIN_SISTEMA;



--==================================== PROCEDURES ===================================

--CREATE PROCEDURE STP_LOGIN
--	@LOGIN VARCHAR(200)
--	,@SENHA VARCHAR(200)
--AS
--BEGIN
--	SELECT * FROM USUARIO
--	WHERE LOGIN_USUARIO = @LOGIN AND SENHA_USUARIO = @SENHA
--END


--EXEC STP_LOGIN 'joao.silva', 'senha123'
